# This is the container name, generated by /container/output.tf/container_name
output "container-name" {
  value       = module.container[*].container-name
  description = "The name of the container"
}

# This ip-address is the ip-address of the container, generated by /container/outputs.tf/ip-address
output "ip-address" {
  value       = flatten(module.container[*].ip-address) # Flatten wraps the array in a single element
  description = "The IP address and external por of the container"
}